version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
  web:
    build: .
    command: npm run start
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  adminer:
    depends_on: 
      - db
    image: adminer
    ports:
      - 8080:8080
    restart: unless-stopped
